### PR TITLE
Add OVP metadata service

### PR DESCRIPTION
**Pull request by itaykinnrot**

### CODE REVIEW

**Comment by tehilar** [comment]
what about using the following for the xml parsing:
https://developer.android.com/training/basics/network-ops/xml.html

**Comment by itaykinnrot** [comment]
@tehilar since the XML is simple and we're not requesting it from a service i dont think we need it - what do you think?

**Comment by tehilar** [comment]
@itaykinnrot  this class is commonly used, i would have used it.

another issue: the new request for the metadata should be created under new service class
named MetadataService and not under the BaseEntry service class. And with a "list" method for this
specific request.

In the KalturaOvpMediaProvider the request call will look like this:

final RequestBuilder entryRequest = BaseEntryService.entryInfo(getApiBaseUrl(), ks,     sessionProvider.partnerId(), entryId)
                    .add(MetadataService.list(getApiBaseUrl(), ks, sessionProvider.partnerId(), entryId))
                    .completion(new OnRequestCompletion() {
                        @Override
                        public void onComplete(ResponseElement response) {
                            PKLog.v(TAG, loadId + ": got response to [" + loadReq + "]" + " isCanceled = " + isCanceled);
                            loadReq = null;

                            try {
                                onEntryInfoMultiResponse(ks, response, (OnMediaLoadCompletion) completion);
                            } catch (InterruptedException e) {
                                interrupted();
                            }
                        }
                    });

**Comment by tehilar** [comment]
i agree on the xml parsing
but please notice the second issue

**Comment by tehilar** [comment]
@itaykinnrot  @noamtamim 
please check changes and approve

**Pull request merged**
