### PR TITLE
Upgrade ExoPlayer version to 2.4.2

### PR DESCRIPTION
**Pull request by ffelini**
The latest versions (2.4.0, 2.4.1, 2.4.2) of ExoPlayer contains lots of [fixes](https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md) and improvements. Would be very nice to have them in PK too.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @ffelini,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by noamtamim** [comment]
@ffelini sdk download is handled automatically by the Android tools. However, this relies on a license key that is only available as a travis secure variable -- which is not available in forks.
I've reverted your gradle/travis changes, and will verify in our repo.

**Comment by noamtamim** [comment]
@ffelini even though this change does not contain any code, I can't accept your PR without a signed CLA: http://bit.ly/KalturaContrib.
Thanks.

**Comment by noamtamim** [comment]
@ffelini direct link to CLA: https://agentcontribs.kaltura.org/

**Comment by noamtamim** [comment]
@ffelini looks like you opened the PR before it's even ready... Please let us know when it's ready and tested, then we'll do our own verification.

**Comment by ffelini** [comment]
@noamtamim This PR was meant only to upgrade the ExoPlayer version but the checks did not pass, that's why it contains other changes in `travis.yml`

CLA is signed, the check had passed.

Don't see anything to add here. Looks like it's ready.

**Comment by noamtamim** [comment]
Pushed to a temporary branch. We'll make adjustments there. 
Thanks!

**Pull request merged**
