### PR TITLE
Reorganize method appeareance in Player.java

### PR DESCRIPTION
**Pull request by AntonAFA**
void prepare(@NonNull PKMediaConfig playerConfig);

    void play();

    void pause();

    void replay();

    void stop();

    void destroy();

    void seekTo(long position);

    void setVolume(float volume);

    void changeTrack(String uniqueId);

    void updatePluginConfig(@NonNull String pluginName, @Nullable Object pluginConfig);

    void addEventListener(@NonNull PKEvent.Listener listener, Enum... events);

    void addStateChangeListener(@NonNull PKEvent.Listener listener);

    void onApplicationPaused();

    void onApplicationResumed();

    boolean isPlaying();

    PlayerView getView();

    long getDuration();

    long getCurrentPosition();

    long getBufferedPosition();

    String getSessionId();

    Settings getSettings();

    interface Settings {

        Settings setContentRequestAdapter(PKRequestParams.Adapter contentRequestAdapter);

        Settings setCea608CaptionsEnabled(boolean cea608CaptionsEnabled);

        Settings useTextureView(boolean useTextureView);
    }

### CODE REVIEW

**Comment by noamtamim** [comment]
Good start. Should be something like:

// ## Playback control
void prepare(@NonNull PKMediaConfig playerConfig);
void play();
void pause();
void replay();
void stop();
void seekTo(long position);
void setVolume(float volume);
void changeTrack(String uniqueId);
boolean isPlaying();
long getDuration();
long getCurrentPosition();
long getBufferedPosition();

// ## Administration
PlayerView getView();
void destroy();
void updatePluginConfig(@NonNull String pluginName, @Nullable Object pluginConfig);
void addEventListener(@NonNull PKEvent.Listener listener, Enum... events);
void addStateChangeListener(@NonNull PKEvent.Listener listener);
void onApplicationPaused();
void onApplicationResumed();
String getSessionId();
Settings getSettings();

**Comment by noamtamim** [comment]
Travis is failing because of the deleted methods prepareNext() and skip() -- they are implemented as stubs in a few places.

**Comment by AntonAFA** [comment]
I know, i just wanted you to see the new order of methods
will fix the build as soon as you approve it.

**Comment by noamtamim** [comment]
Also, please rename the parameter of `prepare()` from `playerConfig` to `mediaConfig`.

**Pull request closed without merging**
